#include <stdio.h>
#include <stdlib.h>
#include <math.h>


/* 

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms. */




unsigned long  Fibonacci(unsigned int n);

static unsigned long total;

int main(){


  unsigned long n = 1;
  unsigned long f = 0;
  total = 0;


  while(f< 4000000){

    f = Fibonacci(n);

    if(f%2==0){
      
      total = total + f;
      
    }else{

      total = total + 0;

    }

    n++;


  }


  printf("Solution to Project Euler problem #2 = ");
  printf("%lu \n",total);




  return 0;




}

unsigned long  Fibonacci(unsigned int n)
{


  if(n==0){
           
    return 0;

  }else if(n==1){

    return 1;

  }else if(n>1){


    return Fibonacci(n-2)+Fibonacci(n-1);


  }

}
